export const FRUITS = [
  "Ackee",
  "Dragonfruit",
  "indian fig",
  "Pear",
  "Pineapple",
  "Apple",
  "Durian",
  "Ice apple",
  "Muskmelon",
  "Grapes",
  "Apricot",
  "Fig",
  "Guava",
  "Naranjilla",
  "Chestnuts",
  "Atemoya",
  "Egg fruit",
  "Jackfruit",
  "Mangosteen",
  "Rosehip",
  "Avocados",
  "Finger",
  "Jujube",
  "Nectarine",
  "Peanut",
  "Banana",
  "Feijoa/Pineapple",
  "guava/Guavasteen",
  "Jenipapo",
  "Passion fruit",
  "Watermelon",
  "Blueberry",
  "Fuyu",
  "Persimmon",
  "Mango",
  "Nance",
  "Tangerine",
  "Black sapote/Chocolate",
  "pudding fruit",
  "Buddha’s hand fruit",
  "Olive	Medlar fruit",
  "Melon",
  "Cantaloupe",
  "Hazelnut",
  "Lucuma	Quince",
  "Strawberries",
  "Cape gooseberry/Inca berry/Physalis	Honeyberries",
  "Rose apple/Water apple",
  "Oranges",
  "Snake fruit/Salak",
  "Chempedak",
  "Horned melon",
  "Mulberry",
  "Ramphal",
  "Rambutan",
  "Cherimoya",
  "Hog plum",
  "Langsat",
  "Papaya",
  "Raspberries",
  "Cherry",
  "Honeydew melon",
  "Longan",
  "Peach",
  "Sapota",
  "Coconut",
  "Kiwi",
  "Lychee",
  "Noni fruit",
  "Star Apple",
  "Custard apple/Sugar apple/Sweetsop",
  "Kabosu",
  "Kaffir lime/Makrut lime",
  "Mouse melon",
  "Starfruit/Carambola",
  "Dates",
  "Kiwano",
  "Lime",
  "Pomegranate",
  "Soursop",
];
